# Generated by Django 4.0.2 on 2022-07-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0003_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('desc', models.TextField()),
            ],
        ),
    ]
